code review
techstudioconsults/Productize-server pull request #48
Opened 2024-05-15 07:13 UTC by obajide028

2024-05-15 10:11 UTC, Intuneteq requested changes

2024-05-15 10:11 UTC, Intuneteq commented on app/Http/Controllers/FaqController.php
Make the following refactor: 

- Instead of using the `all` method on the request data, refactor to use the `validated` method. This way, only validated user data will be passed into the repository method. The `all` method retrieves all inputs from the user, which defeats the point of the request validation injected into controller methods.
- Please ensure that each of your files contains a PHP doc at the top, following the format shown in the image below. This will help everyone working on the files to know who created each file. The "author" section should include your GitHub account username and your name. The version should be 1.0 and the date should be today's date, typically the file creation date.
![image](https://github.com/techstudioconsults/Productize-server/assets/97626624/bc9773e8-ef67-41f1-9e0c-4c664c5cce4a)
- Your controller's methods PHPDoc should typically look like the image below
![image](https://github.com/techstudioconsults/Productize-server/assets/97626624/53f84d44-d3ef-4d7f-91eb-98cafafdb21a)
- Lastly, you need to be consistent with your return data. A collection should return `FaqResource::collection($faq);` while a single resource return should be `return new FaqResource($faq);`. The delete return can remain as it is.

2024-05-15 10:11 UTC, Intuneteq commented on app/Repositories/FaqRepository.php
Make the following refactors

- Change the method name `getById` to `f`indById`
- The Update argument should be the resource and the update array and not the id and the update array
- The delete method argument should be the whole resource and not just the id.

2024-05-15 10:11 UTC, Intuneteq commented on app/Repositories/FaqRepository.php
Add your file naming and method docs also

2024-05-23 13:15 UTC, obajide028 commented on app/Http/Controllers/FaqController.php
Made all the necessary changes in my code

2024-05-23 13:15 UTC, obajide028 commented on app/Repositories/FaqRepository.php
Made all the necessary changes in my code

2024-05-23 13:15 UTC, obajide028 commented on app/Repositories/FaqRepository.php
Made all the necessary changes in my code

2024-05-27 06:05 UTC, Intuneteq approved these changes

2024-05-27 06:06 UTC, Intuneteq requested changes
Please pull the development branch and implement the `Repository` abstract class and ensure your feature and unit tests all pass. Thanks

2024-05-31 11:31 UTC, merged